### ISSUE TITLE
Track upstream code cleanup in stb_vorbis

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#10]
Clang:
- https://github.com/nothings/stb/issues/816 (already addressed in our version)
- https://github.com/nothings/stb/issues/817 (already addressed in our version)

Coverty:
- nothings/stb#838 (closed)
- nothings/stb#839 (fixed in our https://github.com/dreamer/dosbox-staging/pull/71)
- nothings/stb#840 (closed)
- nothings/stb#841 (closed)
- nothings/stb#842 (fixed in our https://github.com/dreamer/dosbox-staging/pull/71)
- nothings/stb#843 (closed)
- nothings/stb#844 (closed)
- nothings/stb#845 (closed)
- nothings/stb#846 (closed)

List created with `echo nothings/stb\#{838..846} | xargs -n1 echo -`

**Comment by krcroft** [comment]
All issues are addressed in our version, so am closing this because they longer affect us.

Upstream STB Vorbis averages three updates per year, so if one or more of these fixes are eventually accepted, then the upstream version will be re-merged.  If they're not accepted, then we will continue to re-apply them to future upstream releases.

**Comment by dreamer** [comment]
Sounds like a plan :) This is more of an "ongoing maintenance" task, than and actionable "issue".
