### ISSUE TITLE
Differentiate nuked vs compat OPL emulators

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#120]
Currently, the documentation states that `nuked` provides the best accuracy while `compat` provides the best quality.  

These adjectives need to be qualified and expanded upon with other traits, to help users.

**Comment by Gamewizard** [comment]
I'll do some audio analysis comparing the two once I get a better analysis chain set up I've all ready done some preliminary work on it, the wording in the docs needs cleaned up as well. I'll touch base with @dreamer  next time I catch him on Discord and see where exactly he's wanting to go.

**Comment by krcroft** [comment]
Thanks @Gamewizard !

**Comment by dreamer** [comment]
Ah, I forgot about to refer this issue in PR, sorry about that. Nuked is not the default OPL emulator in dosbox-staging: #173 

@krcroft do we want this issue closed? Is it actionable?

**Comment by krcroft** [comment]
Yes! I like the new wording.  It differentiates Nuked with just the right amount of detail for users;  thanks for this fixup (closing)
