### ISSUE TITLE
Investigate disappearing texture with auto, metal, and direct3d11 rendering

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#149]
Vogons user **citrixscu** reported:

> DOSBox content within the window disappears if output=texture[nb] and renderer=auto or metal. This is consistent with any SDL2 build I run on this machine, but I can't find much info on what's going on behind the scenes.

https://www.vogons.org/viewtopic.php?p=820547#p820547

**Comment by dreamer** [comment]
Just a tiny reminder: we use `texture_renderer=<value>`, not `renderer`.

**Comment by citrixscu** [comment]
I’ll test some scenarios and report back here.

**Comment by dreamer** [comment]
@citrixscu Thank you so much for testing.

Does it happen with `output=texture`, `texture_renderer=opengl` as well? OpenGL is deprecated in modern macOS, but if we have bugs showing up in metal backend only (or SDL2 metal backend is not up to par), then we might enforce it as default with `auto` (temporarily). I think we'll need to cooperate with SDL2 project to double-check if it's not a bug in there.

**Comment by krcroft** [comment]
Adding a data-point we can exclude: under Mojave (10.14) `metal` is not available; and `software` and `opengl` rendering back-ends are both unaffected.

![2020-01-28_01-22](https://user-images.githubusercontent.com/1557255/73250912-b52b2b00-416c-11ea-860e-e3fd573e6d15.png)

**Comment by citrixscu** [comment]
Hi,

Ran some tests. Please see the output and screenshots below. OpenGL works but as you will see, it looks like scaling does not take place until after the window is moved. If I run in full screen, the output is small on fullscreen until I switch desktops and then come back.

```
[sdl]
fullscreen       = false
windowresolution = 1024x640
output           = texturenb
texture_renderer = auto

[render]
aspect = false
scaler = normal2x
```
Window output invisible
<img width="1210" alt="dosbox-staging-texturenb_auto_or_metal" src="https://user-images.githubusercontent.com/52132984/73288379-bb8ec680-41af-11ea-91d6-b8f9d23feab8.png">

```
[sdl]
fullscreen       = false
windowresolution = 1024x640
output           = texturenb
texture_renderer = opengl

[render]
aspect = false
scaler = normal2x
```
Window output upon launch
<img width="1210" alt="dosbox-staging-texturenb_opengl_before_window_move" src="https://user-images.githubusercontent.com/52132984/73288943-baaa6480-41b0-11ea-89ce-af17303cc3de.png">

Window output after moving window
<img width="1210" alt="dosbox-staging-texturenb_opengl_after_window_move" src="https://user-images.githubusercontent.com/52132984/73288990-c85fea00-41b0-11ea-95ff-3b20752d7ccb.png">

```
[sdl]
fullscreen       = false
windowresolution = 1024x640
output           = software
texture_renderer = opengl

[render]
aspect = false
scaler = normal2x
```
Window output upon launch
<img width="1210" alt="dosbox-staging-texturenb_software" src="https://user-images.githubusercontent.com/52132984/73289067-e62d4f00-41b0-11ea-8990-691208612182.png">

**Comment by GranMinigun** [comment]
> The splash screen is seen, followed briefly by the main DOSBox welcome screen. Then things disappear. When typing, one character can be seen at a time, but disappears shortly after keypress.

Same behaviour with `texute_renderer=direct3d11`. Windows 10 1909, Intel HD 630 w/ latest driver. Will need to also check in-game though.

**Comment by GranMinigun** [comment]
Alright, that's how it looks in-game. My (wild) guess is that only difference from last frame is output - Doom's title screen is static and shown correctly until something starts to appear or move. So could be incorrect framebuffer clean.
![d3d11](https://user-images.githubusercontent.com/11149380/74316857-276e5300-4d9c-11ea-8785-b4443b633f12.png)

**Comment by dreamer** [comment]
@GranMinigun 
When working on a different issue, I managed to reproduce the problem with `output=texture` , `texture_renderer=direct3d11`. Commit, that fixed it for me was test implementation of #177.

For some reason using `output=texture`, `texture_renderer=opengl` started crashing for me (crash happens in OpenGL library) and I can't pinpoint the moment when yet (only on Windows 10, I use AMD  hardware and up-to-date drivers - under Linux it works perfectly, that's why I missed it until now). I implemented additional hack specifically for Windows.

Test this build, please: https://github.com/dreamer/dosbox-staging/actions/runs/55211632

**Comment by dreamer** [comment]
@GranMinigun @citrixscu The fix is waiting for testing in branch `po/gfx-splash-6` - it does solve the problem for me on Windows 10, but more testing will be appreciated. Snapshot builds are in artifacts [here](https://github.com/dreamer/dosbox-staging/pull/222/checks?check_run_id=524144767).

**Comment by dreamer** [comment]
If the problem returns (or was not completely fixed), feel free to reopen this issue :)

**Comment by GranMinigun** [comment]
Works on my machines. So, only MacOS left.

**Comment by citrixscu** [comment]
@dreamer I did a bit of testing on this today and things seem to be working as intended. Apologies on the delay.
