### ISSUE TITLE
Discuss CD-DA Digital Audio Extraction (DAE) requirements

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#176]
I'm re-adding CD-DA digital "read" support for programs that perform DAE, such as MXPlay.  DAE requires providing strict Redbook data back to the DOS program; that is stereo 16-bit, 44.1 kHz samples.  

In contrast to DAE, staging supports CD-DA _Playback_ at whatever frequency and channel-count the compressed track  was encoded at, such as 48 kHz-mono; and each track can have different settings.  We re-configure the mixer's channel dynamically for each track so we can feed it the track's native samples to avoid  resampling or channel duplication.

Back to supporting DAE (strict 44.1-stereo), we have some options and trade-offs:

- **No support**: this is the "do nothing" option and is how CD-DA has been for quite some time.  If you haven't noticed, it's because DAE isn't used by games nor by most CD Player tools; MXPlay appears to be a rarity in this regard - but it's very impressive at what it does.

- **Partial support**: we would support DAE so long as the compressed track can natively decode to a Redbook compliant stream; which means using 44.1 stereo when compressing to Vorbis, MP3, and FLAC.  Opus is left out - because it upsamples to 48 kHz. We would print an error message if the track can't support DAE.

- **Full support**:  We would resample as-needed to deliver 44.1 kHz samples, as well as _up-channel_  moni tracks to stereo. This is ideal from a technical perspective and gives the user maximum flexibility with consistent results, but adds a runtime dependency in the form of a high-quality resampling library such as `speexdsp` or `soxr`.

  Both `speexdsp` and `soxr` are commonly available cross-platform, even on Windows via `vcpkg`. So the "con" here isn't that bad (we're still dwarfed by SDL, which has 37 library dependencies on my system).  You might also recall the early implementation of the CD-DA patch also used SpeexDSP for resampling - so it's not too onerous. 

   If we prefer this option, our goal is to decide which resampler we prefer; and most importantly one that will gives us the least cross-platform support issues. (it's also not the end of the world if we want to change our mind  after some years.. resamplers have a pretty common interface and will be easy to tradeout).

**Comment by dreamer** [comment]
Opus can also use 44.1kHz, I believe? I wonder if there are any games, that might use digital audio extraction… seems like a simple DRM measure.

**Comment by dreamer** [comment]
Ops, closed it by mistake.

Opus can use 44.1kHz as well, right?

I wonder if there are any games, that use it… perhaps only as some sort of crude DRM measure, but maybe there are other use-cases as well. My thoughts on this are:

**No support** - acceptable, as we're focused on games and not productivity software… and we don't support CD-DA from physical CDs, so user always has an option of creating .CUEs first.

**Partial support** - I think this is the preferred solution, at least for the first iteration (unless it will add a lot of complexity to dosbox-staging code, which I presume won't be the case?). Basically I see no drawbacks, and additional functionality will probably useful for someone, somewhere out there - maybe not for games, but that's not a be-all-end-all :)

**Full support** - To be discussed after partial support will be in, I guess; even when implemented, we should still print warning message to the user about resampling.

**Comment by krcroft** [comment]
Opus uses powers-of-two, and a transparent resampler (noise floor below -96dB) to super-sample inbound signals. Sub-12kHz inputs are super-sampled to 24 kHz; and those above that are super-sampled (and played-back) at 48 kHz. Given even VOIP calls are now wide-band, almost all Opus encoding are at 48 kHz.

**Comment by krcroft** [comment]
Regarding partial vs full support; we can get another perspective from upstream, which has "full" support for DAE. That is, it supports DAE regardless if you're using physical CDs, BIN/CUE, or any compressed CUE track that DOSBox is willing to mount (granted, that's already constrained to stereo, 44.1

**Comment by krcroft** [comment]
After some investigation, the SoX resampling library is available in all popular package managers on Linux, Windows, and Mac; plus the BSDs and even AmigaOS4's (which provides the SoX command-line resampler). 

SoX is both faster and higher quality (noise floor below -170dB), than the SpeexDSP resampler). Although both are considered extremely fast and transparent to listeners.. so I'm in over-spec land here

**Comment by krcroft** [comment]
> To be discussed after partial support will be in

Sounds like a plan! will drop in partial support for PR first. 

> I guess; even when implemented, we should still print warning message to the user about resampling

Two reasons against printing a warning: 

- There is no precedent for it; DOSBox itself already resamples each mixers' channel to the common mixer-rate (if any of them differ) - and does so without any warnings. 
The external sound sink (such as pulse audio, alsa, directX, et ) will again resample that to the sound card's prefered sink rate (typically 48 kHz); and none of those warn the user.  So there's a whole lot of resampling going on without warning. 

- Of all of this resampling, we will objectively be using a resampler that exceeds all human thresholds of detectability by more than 10-fold (unlike some resamplers listed above, which no doubt can be detected in listening tests).

**Comment by krcroft** [comment]
Partial support is inbound.

**Comment by krcroft** [comment]
Here's a comparison of SpeedDSP vs SoX at comparable performance measures :

![2020-02-17_12-34](https://user-images.githubusercontent.com/1557255/74684852-d1c1ee00-5181-11ea-939f-2255dab3abae.png)

The dark blue and purple lines in the SpeexDSP graph show noise introduced around the -100 dB mark; which is quieter than the 16-bit [quantization noise on a CDROM](https://en.wikipedia.org/wiki/Comparison_of_analog_and_digital_recording#Quantization
).  So if someone objects to this, then they shouldn't even be listening to CDs - because the simply fact of digitizing the samples on a CDROM comes with roughly twice noise (being roughly 3 dB greater) than what SpeexDSP introduces!

All of this to say - both are top-notch resamplers; however we might as well pick the faster and more accurate resampler; even if our ears won't know the difference :-)

**Comment by krcroft** [comment]
Discussion concluded; implementation underway.  Closing.
