### ISSUE TITLE
Improve freeing of resources on exit, to do them manually and to not rely on OS.

### ISSUE THREAD

**Issue by kas1e** [dreamer/dosbox-staging#180]
As of now, some resources are not freed on exit, and they left to be handled via OS. But not all OS are free resources for programmers (probably its only windows, Linux, and macOS (?)  do so). At least on AmigaOS4, MorphOS and AROS developers should free resources ourselves.

In our case, we didn't free OpenGL context when need it (when we exit from DOSBox for example) and that causes issues on OSes that don't do dirty work for programmers. We also didn't destroy the window, renderer, and co if the user hit close gadget or exit from.

In my local build, I fixed it just by adding to the current, almost empty, ```SDL_Quit_Wrapper()``` function that kind of code:

```C
static void SDL_Quit_Wrapper(void)
{
#if C_OPENGL
    if (sdl.opengl.context) {
        SDL_GL_DeleteContext(sdl.opengl.context);
        sdl.opengl.context = 0;
    }
#endif

    if (sdl.renderer) {
        SDL_DestroyRenderer(sdl.renderer);
        sdl.renderer = NULL;
    }

    if (sdl.texture.pixelFormat) {
        SDL_FreeFormat(sdl.texture.pixelFormat);
        sdl.texture.pixelFormat = 0;
    }

    if (sdl.texture.texture) {
        SDL_DestroyTexture(sdl.texture.texture);
        sdl.texture.texture = 0;
    }
#ifdef NOLOCK
    if (surface_NOLOCK) {
        SDL_FreeSurface(surface_NOLOCK);
        surface_NOLOCK = 0;
    }
#endif

    if(sdl.window) {
        SDL_DestroyWindow(sdl.window);
        sdl.window =0;
    }
    
    SDL_Quit();
}
```

That did the trick. But I not sure of course if it only one place where such stuff need to be added. But at least with that, it fixes OpenGL didn't die anymore with waiting on exit when use "output=opengl", or "output=texture with texture_renderer=opengl".

**Comment by krcroft** [comment]
@kas1e , thanks again for another fix; we should be cleaning up all SDL resources that have a corresponding Destroy/ Free call for them, so next step is putting these into a commit and testing them on various platforms.  

Besides SDL objects, DOSBox has many memory allocations that aren't released on  proper close, and eveb more aren't released  on an unexpected or crashing close.  Is AmigaOS4's total free memory decremented in either of these cases? (ie: once a program leaks memory, the amount is permanently unavailable to the OS until the next reboot?).

**Comment by dreamer** [comment]
I would much rather see a PR than changes suggested via issue comments :/ Right now I have no idea who wants to work on this - or should I start working on it? Do we have duplication of effort already? Whom should we credit for developing the change as commit author to show in `git blame`?

@kas1e are you preparing PR in the background?

**Comment by dreamer** [comment]
Oh, and I consider memory leak to be a bug - no matter what OS. If it happens to not cause problems on Linux, then it's nice - but we still need to fix it.

**Comment by kas1e** [comment]
@dreamer 
No no, i only post snipets of code to show logic, etc on which someone with better dosbox and sdl knowledge can made a better commit.

**Comment by dreamer** [comment]
@kas1e I just needed clarification to avoid people stepping on each other's toes, thank you! :)

**Comment by dreamer** [comment]
I started working on this on branch `po/sdl-cleanup-1`; overall this sequence of destroying resources is pretty similar to the sequence in `GFX_SetSDLWindowMode`, so I hope code duplication could be avoided. Also, perhaps this implementation cleans up our dynamic analysis report a little bit? - to be investigated :)

**Comment by dreamer** [comment]
@kas1e Can be tested on branch `po/gfx-splash-6-ppc`, as other related fixes. Please confirm if it works ok :)

**Comment by dreamer** [comment]
If the problem returns (or was not completely fixed), feel free to reopen this issue :)
