### ISSUE TITLE
GCC under macOS fails to build DOSBox

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#19]
```
In file included from midi_coremidi.h:17,
                 from midi.cpp:75:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:304:2: error: expected unqualified-id before '^' token
  304 | (^MIDINotifyBlock)(const MIDINotification *message);
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:304:2: error: expected ')' before '^' token
  304 | (^MIDINotifyBlock)(const MIDINotification *message);
      | ~^
      |  )
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:347:2: error: expected unqualified-id before '^' token
  347 | (^MIDIReadBlock)(const MIDIPacketList *pktlist, void * __nullable srcConnRefCon);
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:347:2: error: expected ')' before '^' token
  347 | (^MIDIReadBlock)(const MIDIPacketList *pktlist, void * __nullable srcConnRefCon);
```

**Comment by krcroft** [comment]
Will try prior gcc versions as well.

**Comment by krcroft** [comment]
Someone on Vogons hit this 8 years ago.

@dominus mentioned setting environment variables but could not recall them - and searching and googling turns up nothing. 

Will check with Dominus to see what he thinks: 
https://www.vogons.org/viewtopic.php?f=32&t=29033&p=796740#p796740

**Comment by dreamer** [comment]
The code does not compile, because of this

MidiServices.h:

    303: typedef void
    304: (^MIDINotifyBlock)(const MIDINotification *message);

I've never seen this syntax before… turns out it's Apple's extension to C language, which is not available in GCC: https://en.wikipedia.org/wiki/Blocks_(C_language_extension)

**Comment by krcroft** [comment]
Fully agree. 

The fact that DOSBox is directly pulling in headers that aren't in any way part of the C or C++ language specifications (at any point in the past nor proposed in future ammendments) conflicts with the use of existing C and C++ specifications, such as those ratified > circa-2000.

Regardless of the above, surely anyone would agree these Apple headers are undesirable, and perhaps the cause is auto-tools package or pkg-config trying to make the best of things.  But in any case, it seams worthwhile that DOSBox at a minimum compile using a current GNU build stack (on the 2nd-most-popular desktop OS no less).

My solution would be to carve this cancerous portion of functionality out of the code via detection of gcc in the build system or ideally have these AppleBlocks reveal themselves with some preprocessor definitions: so at least we get full coverage with the GNU build stack, minus midi functionality. 

The CoreMIDI package probably boils down to C-callable symbols, so a more elegant solution might be to write a C-compliant shim-header with extern prototypes for those (few?) midi calls DOSBox relies on. But that's something I have little interest in doing.

**Comment by krcroft** [comment]
Looks like we can detect and work-around it; something like:
```
#ifndef __has_feature
    #define __has_feature(x) 0
#endif

#if __has_extension(blocks)
    ... include CoreMIDI rubbish
#else 
    ... C/C++-compliant code path  
#endif
```
https://clang.llvm.org/docs/LanguageExtensions.html#blocks
http://releases.llvm.org/3.7.0/tools/clang/docs/LanguageExtensions.html#has-feature-and-has-extension

**Comment by krcroft** [comment]
Fixed in https://github.com/dreamer/dosbox-staging/commit/e035f8bc602da2770dcc47a2e9f39d6a51c552c7

Will see what up-stream thinks; will close this for now knowing we have this solved in the iterim to keep the CI chain ticking along.

PS - wow.. gcc-6 detects 226 additional warnings when building under Mac: https://github.com/dreamer/dosbox-staging/runs/275764609

**Comment by dreamer** [comment]
Ouch, that's a lot… It seems like most of them are `strict-aliasing` warnings.
