### ISSUE TITLE
Lack of "newline" at return to DOS prompt

### ISSUE THREAD

**Issue by datapackrat** [dreamer/dosbox-staging#208]
Lack of "newline" at return to DOS prompt.  For example, this leaves the prompt at the end of whatever text was printed last.

![Example](https://user-images.githubusercontent.com/60073109/76439527-e7968d80-6392-11ea-86a1-2d822cce949d.png)

In both cases, a CLS command was used before the visible command.  In 0.74-3, there is an extra newline causing a blank line at the top of the screen.  In dosbox-staging-windows-v0.75.0-pre-613-gf202, there is no extra blank line at the top of the screen, but the lack of a newline at return to COMMAND leaves the DOS prompt at the end of text from the program.

**Comment by dreamer** [comment]
This change was, in fact, made on purpose: b0cdfa51618b4ef31d0e9b9a5b974241cc6d206b (and broken `cls` command was one of motivating factors for this fix). Now the behaviour of dosbox-staging internal shell is consistent with all other modern shells out there - and misbehaving programs, that don't print newline after output - well they are the buggy ones.

However, I won't close this bug report just yet. We already fixed all (I hope) internal DOSBox commands to consistently print newline after output; this bug report gave me an idea how to solve it for old DOS programs as well, but I need to do some testing; stay tuned and thanks for a bug report :)
