### ISSUE TITLE
Adopt and enforce a Code of Conduct

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#216]
**Motivation:** A code of conduct will facilitate healthy, constructive community behavior for all involved. It will prevent unproductive attitudes, toxic behavior, and low-signal-to-noise content from draining our collective efforts.

**Expectations:** We, collectively, are the life-blood of this project. The CoC will ensure this is a place where we can expect to participate in productive and progressive discussions and ideas about DOSBox and its future.

**Benefits of Enforcement:** Enforcing a CoC will bring predictability and confidence for all participants. non-CoC-compliant comments will knowingly be purged to maintain a high signal-to noise ratio.  As volunteers, we (as testers, developers, issue-reporters, idea generators, documentors) can stay focused on progressing what we love: DOSBox and the golden age of DOS gaming!

**Comment by krcroft** [comment]
In reviewing many open source codes of conduct, I found this one the aligned well with my own opinions:

https://github.com/yahoo/yfuzz/blob/master/Code-of-Conduct.md

Apache's has decent parts: https://www.apache.org/foundation/policies/conduct

I like the overt and concise spirit of this one: https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/code-of-conduct.md

A couple other that we can pick parts from:
- https://github.com/whiteoctober/open-source-code-of-conduct/blob/master/code_of_conduct.md
- https://www.contributor-covenant.org/version/2/0/code_of_conduct/

**Comment by JoshuaFern** [comment]
**Legal:** It's important to first state that this is not a legal document like a license, instead it's more like a set of club rules for a clubhouse.

**Management:** We can define a restriction of powers. Although project management must self-govern their own restrictions as no one is higher than them. At the end of the day management for any project can ban anyone for any reason.

**Weaponization:** It can be used as a weapon to satisfy personal vendettas, i.e. I don't like Ted, so I'm going to go out of my way to apply the rules against him in particular. Maybe by taking advantage of some ambiguous wording or uneven enforcement. For example, "Be excellent to each other" is simple enough for a child to understand but so vague almost anything could be a violation. I believe that simple rules is the right choice however, although it could be easily weaponized we should trust that project management has the best intentions and won't target individuals. If not we have a core problem that a CoC can't deal with.

**Social Issues:** CoCs are notorious for siring up controversy by touching on sensitive social issues. For this reason rules should simply apply to all humans equally _without_ pointing out our differences. 

**Proactive vs Reactive:** So far most CoCs focus on what **not to** do, as if they're creating a list of rules that will result in punishment. Remember that project management has the power to do whatever they want regardless. I think there's great potential for using the CoC more as a learning tool of how to interact socially, by providing examples and explanations of desired behavior. Let's keep a positive and proactive attitude instead by focusing on what **to** do. I believe this is the secret to making an effective Code of Conduct that's enlightening to read and results in a great community by humanizing and uplifting everyone.

**Comment by krcroft** [comment]
> Let's keep a positive and proactive attitude instead by focusing on what to do. I believe this is the secret to making an effective Code of Conduct that's enlightening to read and results in a great community by humanizing and uplifting everyone.

Couldn't have said it better!

I want everyone to experience the positive growth and reward I've had in collaborating on an open-source project.  I know many have very few minutes or hours per day or even per week, so this needs to be a place where we can guarantee those excellent aspects you described @JoshuaFern.

I owe it to you and others that, when you step away from your PC, you should be no worse off and ideally feeling better, more confident, and more grounded about the situation here in this repo that before you sat down at your PC.

I feel that projects like this can teach far greater than what one can learn in a paid office environment, because they are biased by money in both directions. Putting food on the table makes us all endure (or get away with) some level of toxicity to keep the money flowing.  Fortunately we don't have that bias, and our only currency here is partiaking in rewarding experience. 

I'll throw together a draft CoC in the next couple days and we all can peel it down to the essence of what we want to achieve.

**Comment by JoshuaFern** [comment]
> I feel that projects like this can teach more about cooperative behavior than a paid office environment, because commercial endeavours are financially biased: putting food on the table makes us all endure (or get away with dishing out) some level of toxicity. Companies tolerate it both ways to keep the money flowing. Fortunately we don't have that bias, and the only currency we can put in your pocket is a rewarding experience.

Absolutely, this is the difference between a company and a non-profit. One provides monetary growth, the other personal growth.

Toxicity is the misdirected shadow of personal turmoil. Nobody wants to work within a venomous social scope, but people are still people. We don't know what they've been through and should give them the benefit of the doubt and treat them with care and respect in all communications, else we risk fueling the same toxic tendencies in ourselves.

**Comment by krcroft** [comment]
> We don't know what they've been through and should give them the benefit of the doubt and treat them with care and respect in all communications, else we risk fueling the same toxic tendencies in ourselves.

We will all strive to be forgiving teachers, learners, and hopefully rarely policers.

**Comment by JoshuaFern** [comment]
@krcroft This can be closed :)

**Comment by krcroft** [comment]
Thanks for the reminder @JoshuaFern. Closing.
