### ISSUE TITLE
Joystick not getting passed through to games

### ISSUE THREAD

**Issue by mdmallardi** [dreamer/dosbox-staging#219]
Hi, I'm trying to use an old Saitek ST290 Pro joystick with some dosbox games.  Dosbox 0.74-3 detects it and passes it through to my games (Testing currently with Wing Commander Privateer), It's detected as a 4axis when joystick type is set to auto.  dosbox-staging claims to see it, but does not pass joystick information on to the game I am testing with.  Thanks for your consideration and time.

Additionally, dosbox-staging does not seem to detect the joystick at all when I set the type manually to 2axis.

**Comment by dreamer** [comment]
What OS are you testing on? I haven't worked too much on joystick emulation yet, but that code was heavily touched during the transition to SDL2, it's very probable we introduced regressions.

The (very limited) tests I performed so far we done via controller remapping in Steam, so maybe they were not even touching joystick emulation code at all.

**Comment by krcroft** [comment]
Confirmed on Linux with a Gravis F310 in X-Input mode. Thanks for the report @mdmallardi !

**Comment by mdmallardi** [comment]
I'm testing on Arch Linux.

**Comment by krcroft** [comment]
Quickly skimmed through the joystick code. It's involved with lots of provisions for various axis and numbers of buttons. My guess is much of this handles various SDL1 cases, which hopefully SDL2 has simplified or abstracted given the huge number of controllers they now support.

DOSBox is nicely architected, and we typically have something like this:

```
Emulated DOS (interrupts/BIOS) | <- DOSBox logic -> | <- SDL2 API calls -> | <- OS-API (X-Input/Direct-X/..)-> | <- host drivers (USB-HID) -> | <- joystick -> | <- your hand
```

Ideally with SDL2, we can work up from first principles and offload as much DOSBox joystick management into SDL2 size as possible; reducing the DOSBox portion to a shim. (me <- fully expecting reality to be entirely different from this fantasy!)

I suppose the fact this only just now has been reported shows how many users actually use joysticks in DOS games :-)  I remember having a Gravis gamepad back in the day; and it eventually started drifting. No amount of fixed helped it, and I eventually tossed it in frustration.  Back to binary on-off steering cars and banking aircraft. Lol.

**Comment by bitstrom** [comment]
After removing line 2585 from sdl_mapper.cpp my gamepad started working. 

[https://github.com/dreamer/dosbox-staging/blob/01f5ca4365e4c3748f895a8948707ec09c162846/src/gui/sdl_mapper.cpp#L2585](url)

**Comment by mdmallardi** [comment]
I can confirm that @bitstrom 's solution works as well.  However, while this may be a hardware issue with my joystick, holding the trigger button isn't polled as repeated input, but this does work with my DualShock 4 controllers as expected.

**Comment by dreamer** [comment]
That line (whole function in fact) was added to support feature of reloading of keymapper files in runtime - just removing it is likely to break that feature; without actually looking in details into the code yet - I **suspect**, that removing `MAPPER_Init` call from [`sdlmain.cpp:2827`](https://github.com/dreamer/dosbox-staging/blob/01f5ca4365e4c3748f895a8948707ec09c162846/src/gui/sdlmain.cpp#L2827) might be better. Mapper initialization on startup happens in sdl_mapper.cpp:2590 already (I haven't confirmed this yet - it's only speculation on my part).

**Comment by mdmallardi** [comment]
Sadly, removing sdlmain.cpp:2827 does not resolve the joystick issue.  However, removing sdl_mapper.cpp:2585 does.

**Comment by krcroft** [comment]
@mdmallardi , @bitstrom, @dreamer - I just pushed branch `kc/joystick-fixes-1`, and will move it to draft PR.

At the core this follows @bitstrom's solution, plus some logic clean cleanup and added safety checks. I don't think we've dropped any functionality - but please kick the tires.  The commits describe the intent.

**Comment by mdmallardi** [comment]
@krcroft's PR seems to handle all issues well to me.

**Comment by krcroft** [comment]
Thanks for tesing on your system @mdmallardi .  I've temporarily pulled the PR with some new ideas for how to make it more robust. Will keep you posted!

**Comment by krcroft** [comment]
@mdmallardi , round two is ready! If you have a chance, please give `kc/joystick-fixes-2` a go.
This solution is much more robust, but at the same time introduce more change than the prior branch.

It also prevents the mapper from leaking, which was one of its strong points. So please use the mapper and see if you get segfaults or bus-errors when quitting back to the shell (which would be caused by double-free).

**Comment by mdmallardi** [comment]
After testing quite a bit this evening, I found no glaring issues!

**Comment by krcroft** [comment]
Thank you @mdmallardi!

**Comment by dreamer** [comment]
@mdmallardi Issue got closed automatically with the review, but there were some additional changes after you tests. According to our testing it's still ok, but if we missed something - feel free to reopen the issue (or leave a note for me to reopen, as I see you're responding via mail).

Thanks for report anyway, have fun! :)
