### ISSUE TITLE
Automate regression testing 

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#23]
Automated regression testing would let us make changes with the confidence that functionality and performance regressions are caught fast. 

To avoid changing DOSBox's internal code (with whitebox tests), a blackbox approach would allow non-developers to contribute cases. 

A test case would involve feeding DOSBox a custom dosbox.conf file (setting particular features), running a DOS program that generates some capturable result (then quits on its own when done), and finally comparing the captured result to a previously saved known-good result.

The test harness could also record metadata such as test runtime, memory usage, latency, etc - so performance and resource uses could at least be measured and more importantly trended or flagged. (although some tolerance would be included as we aren't guaranteed isolated and identical CI VM hardware). 

Getting this off the ground would involve modifying DOSBox so it can run headless; currently it fails to even start if SDL can't latch onto an active display.  We would need to find or write representative DOS programs that exercise some singular element of common game functionality: real mode, protected mode, EGA, VGA, SoundBlaster, GUS, and so on. For now, simply having DOSBox run "hello world" would let us get the framework in place.

**Comment by dreamer** [comment]
Yeah, I was thinking about a similar thing recently - I am working on a small patch, that would fix a bug with text output inside DOS prompt and I got extremely annoyed at inability to test it quickly...

We need at least two kinds of automated testing:

- blackbox tests, exactly as you described; I will experiment with setting up display-free dosbox instance in SDL2 work.
- unit tests, to avoid introducing regressions for functionality that's already written.

I think both of these improvements would be easier to introduce after implementing better buildsystem first (e.g. to avoid duplication of code infrastructure where it comes to harnessing test results, coverage results, etc). Automake/autoconf is too annoying to work as it is.

Personally I have the most experience with Googletest (Gmock is included nowadays, thankfully) - it's Unit Test framework, but it can be creatively used for all kinds of testing (if code infrastructure is in place). Git project (as in: git client) uses blackbox tests written in bash with `prove` (perl-Test-Harness) and a Makefile used to orchestrate them - it's a bit weird setup but works surprisingly well and could be used for inspiration here.

**Comment by krcroft** [comment]
Excellent point regarding the build system; agree that's what needs solving first to avoid throwing-away effort into the auto-tools abyss.

Glad you have hands on with some top-notch test frameworks; I will get familiar with them.

**Comment by krcroft** [comment]
Adding this for future reference:
https://discourse.libsdl.org/t/possible-to-run-sdl2-headless/25665

**Comment by LowLevelMahn** [comment]
Ideas:

**More static analyzers:**
-add (open source) cppcheck 
-PVS Studio (free for Open Source) - really good results
-add staging as Coverity Scan project: https://scan.coverity.com/

**For better coverage while testing with the Sanitizers:**
-collect DOS Games (Demos or Free) that have a Doom-like Demo/Replay Mode that can be triggered from extern (using various aspects of DOSBox: Filesystem, Grafik, Sound, ...)
-> Dosbox Community could be of great help here
-uses QEMU cpu unit-tests: see https://github.com/xor2003/masm2c/tree/master/qemu_tests for example, there are much more in qemu git: https://github.com/qemu/qemu/tree/master/tests
-check Coverage (gcov, https://clang.llvm.org/docs/SourceBasedCodeCoverage.html)  of these Demos/Tests on DOSBox (what parts are missing using the tests - find more demos etc.)

**Comment by LowLevelMahn** [comment]
According to the Scan page there is still a build or something missing for Coverity Scan

**Comment by krcroft** [comment]
@LowLevelMahn , I just logged into Coverty and all looks fine; can you please attach a screenshot of what you're seeing from your side?

**Comment by LowLevelMahn** [comment]
![image](https://user-images.githubusercontent.com/580819/69626230-826b9600-1048-11ea-9543-4117f6a6848b.png)

**Comment by LowLevelMahn** [comment]
![image](https://user-images.githubusercontent.com/580819/69626284-9e6f3780-1048-11ea-96e0-a34ffc2b6326.png)

**Comment by krcroft** [comment]
https://scan.coverity.com/projects/dosbox-staging

**Comment by LowLevelMahn** [comment]
Works

**Comment by LowLevelMahn** [comment]
add project requested, interested in finding out the finding differences between cppcheck, pvs-check and coverity

**Comment by LowLevelMahn** [comment]
how often is the Coverity Scan update with the current source build?

for example: 

your fix in: https://github.com/dreamer/dosbox-staging/commit/723dfdbe46adb83da4e48d52d5655d7408a4f90d

is still an uninit bug in Coverity.Scan

**Comment by krcroft** [comment]
@LowLevelMahn , can you 
 confirm you have access to the Coverty page now? I see you in the members list, so @dreamer might have added you. 

So far I've only ran a couple manual builds through it out of curiosity for what it produces.  

I only want to add stuff to our CI flow if we plan to make use of it; are you interested in working with it's output -- maybe fixing issues that it reports?

If yes, that would be a very welcome help to the project and justify adding it to our code analysis workflow!

**Comment by LowLevelMahn** [comment]
> If yes, that would be a very welcome help to the project and justify adding it to our code analysis workflow!

Coverity.Scan make only sense when integrated into a CI process - or else you always see old findings and stop trusting in Scan - i hope to start fixing some low hanging fruits - there are enough findings for everyone :)

**Comment by krcroft** [comment]
You beat me to my edited comment where I mention adding a regular build and upload :-).  Will add it today.

**Comment by dreamer** [comment]
AFAIK, Coverity on CI works only with Travis. We could add it as a secondary static analysis scan (that would be fine by me - having static analysis in the form of a linkable report would be very useful - and quality of issues detected is ok as well).

I have some experience with using Coverity, though… I used it at work, at 2 different companies. In both cases, teams decided to stop using it in favour of Clang static analyzer. The main issue was inability to easily run scan locally, to verify that your commit actually fixes things before push / during review. This is very frustrating, and the issues detected by Coverity got unaddressed for long time in the result. I also tried to follow Coverity scans for open source projects - with similar problems.

I registered dosbox-staging for Coverity some time ago, but got disinterested after they told me to wait several days before I could make my first scan… Great to see @krcroft following through with it, tough! :)

**Comment by dreamer** [comment]
Coverity offers only up to 21 builds per week / 3 builds per day: https://scan.coverity.com/faq#frequency 

I'm not sure if it's enough even if set only for master branch… They recommend creating a branch specific for static analysis and move it to the commit, that we want checked.

**Comment by dreamer** [comment]
Eh, I tried setting up Coverity via Travis, but I give up: https://travis-ci.com/dreamer/dosbox-staging (the key is exactly copied from Coverity page). My suspicion here is: Coverity is still referring to *travis.org domains everywhere, but Travis stopped using it for free accounts about a year ago, now ALL accounts trigger builds on *travis.com. dosbox-staging repo is registered for both domains (Coverity has no idea, that *.com even exists).

I am not going to spend more time on this, but will gladly accept PR turning on Coverity trigger via Travis.

**Comment by krcroft** [comment]
@dreamer @LowLevelMahn ; bad progress on my side too.
- Coverty's tarball can't be downloaded directly; it requires a valid login session. I ask them for help last night (still unanswered ~20 hours later), and had no luck trying with their token/email syntax for uploads.
- Fallback approach is hosting that tarball publicly in Google docs, and it can be cut into roughly a quarter of it's size using `rm -rf closure-compiler jars jdk11 jre node support-angularjs ; cd bin; rm *java* *js* *php* *python* *ruby*`, resulting in an 86 MB tar.zstd.  
- So let's assume that's solved, do we like the solution?
  - If it's part of our CI chain, we'll blown through those 21 scans almost instantly.
  - Uploading is asynchronous, so feedback will always be positive
  - The webUI is circa-2000's without any structured way to gather it, so really the only feedback loop is a human scrolling through it

The only workflow option I see is:
- Once a week we run a Coverty build and push, say from master.  We'd have a dedicated YAML, say `coverty.yml` triggered using`[ on.schedule](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule)`. 
- That leaves ~17 manual upload & view cycles to whoever wants them.
- We then use coverty badge as our coarse feedback counter as PRs pour into master.

**Comment by LowLevelMahn** [comment]
> Once a week we run a Coverty build and push, say from master. We'd have a dedicated YAML, say coverty.yml triggered using on.schedule.

i think that is good enough - there are still clang-analyzer, cppcheck, pvs-studio available
maybe Coverity is just a before-release-thing

**Comment by krcroft** [comment]
Here's a tentative workflow.
https://github.com/dreamer/dosbox-staging/compare/kc/coverty-scan-1
I'll switch the trigger to "push" when the secrets are in, and see how it goes.

**Comment by dreamer** [comment]
Coverity daily builds are now merged to master, thanks @krcroft !

I added a badge to WIP readme file, can be viewed here: https://github.com/dreamer/dosbox-staging/tree/po/readme-1

**Comment by dreamer** [comment]
We have a tiny problem with Coverity (with the way Coverity is presenting results). Today, Coverity shows "12 new warnings", which is misleading, because no new commits landed in the master branch since yesterday.

The reason why these "12 new warnings" are detected, is because @krcroft is working on fixing them on his own branch, and hist test coverity run got classified as project status for yesterday (field "Version" on Coverity status page now says refs/heads/master, but yesterday it was krcroft's branch).

So what do we do about this? Should I remove Coverity badge from README.md to avoid showing misleading status? Is there some way to force Coverity to not show misleading status?

**Comment by krcroft** [comment]
Coverity uses a "dumb" diff between the current and prior run; so unfortunately the badge is misleading (at the worst) and meaningless at best, because when the delta between runs is zero the badge simply reports "passing", which doesn't say much (given we still have hundreds of open issues).  My vote is to knock it out.

**Comment by krcroft** [comment]
Propose we close this issue. 

We have the hooks in place to run tests (yes, nothing fancy and no frameworks right now) - however, the big missing piece are DOS executables that exercise a particular feature, write some output to a text file (good or bad), and then quit.

Once we have those, then our test coverage will grow beyond the simple "start and quit" testcase currently being run.

**Comment by LowLevelMahn** [comment]
what about asking the Dosbox-Community for help - one part are special test programs, but also games /demos/benchmarks/sound players/... can be good test-cases?

**Comment by krcroft** [comment]
Yes to all :-)

There are two key parts to a DOS test executable:
 1) Perform some task, then quit
 2) Leave behind some post-facto indication (text file) if said work was successful

So even though most demo's meet the first criteria, I'm not sure how they meet the second.  Do you know of any tools that meet these (or have other ideas of how to "capture success").  

Otherwise I _think_ we need some custom-written tools for this; and absolutely need to community to help write these. (video-mode checkers, audio-card checkers, midi checkers, and so on).

**Comment by LowLevelMahn** [comment]
> Do you know of any tools that meet these (or have other ideas of how to "capture success").

unit-like testing
there is a qemu test-suite for the CPU - and other hardware-tests available: exmple: https://github.com/xor2003/masm2c/tree/master/qemu_tests
maybe they can be adapted

coverage-raising
the other idea is to just get a bunch of demos/apps together and look what coverage can be reached
combining them all, fill the holes with more demos/apps and then let ASAN run

**Comment by LowLevelMahn** [comment]
another one: https://www.philscomputerlab.com/dos-benchmark-pack.html#

**Comment by LowLevelMahn** [comment]
it would be so great to have some sort of CI/Server that can be extended (easily) by the community to raise the coverage - like a game for glory and honor, "i've reached the 100% with my submit"...
with upload size and runtime limit

coverage build + testprogram (needs to run unattended from the dosbox.conf)
then a feedback if the submit raised the coverage of what part

something like that on a web-pages:
![image](https://user-images.githubusercontent.com/580819/70077305-da823980-1600-11ea-8ec5-50cb10983131.png)

maybe these online coverage service are able to do that

**Comment by dreamer** [comment]
> maybe some of the simpler components can be fuzzy tested?:
> 
> * http://lcamtuf.coredump.cx/afl/

Thanks for this suggestion. I know lcamtuf's work - and it is stellar. I think we can utilize his fuzzer to bruise DOSBox in a variety of ways (I think we could fuzz easily fuzz .conf files, iso files, .cue files, mapper files, some batch scripts; with a some more work I think we could probably fuzz some DOS binaries as well).

**Comment by krcroft** [comment]
_"have we harmed any existing features?"_  is what I'm after. 

Our new code might have add a new and rare corner-case memory bug that fuzzy lopping will one day uncover, but that's secondary to making sure our new code actually still meets the sunny-day scenario for users. 

I'm very fearful of this: _"Sorry guys; turns out my new C++11 code, which squashed 100 warnings, fixed 30 static analysis bugs, and is half the lines-of-code, now causes a hang when games query for Gravis Ultrasound on port 240"_.  Because it's happened to me: my audio code broken CD-DA volume control and channel control until it was pointed out by ECE users on vogons. 

I'm also worried that our ability to re-write new or upgrade-old-C++ to C++11 will exceed our ability to deeply test all the use case permutations.

@LowLevelMahn - I like your idea regarding test coverage.  Maybe we could provide instrumented binaries to the community that users run through their personal gauntlet of games and then send back their `gcov` file.  It wouldn't take long until we have almost all of those sunny-day scenarios covered, and we could stamp an official release version on the binary and call it done.

**Comment by dreamer** [comment]
Coverity and Synopsys are starting to be ridiculous. Their outage lasts 4 days already, they do not respond to mails, and do not acknowledge the problem exists (on a community forum, someone from Synopsys advised us to "send a mail" to the addres, that does not respond to our repeating mails :/).

Yesterday we disabled nightly Coverity scans in a hope, that this will move our build faster to the front of the queue. When we did this, there were 194 other builds ahead of us. Now there are **309** - this makes no sense at all.

**Comment by krcroft** [comment]
Synopsys appears to be a heavily closed up company with what appears to be 90s-style internal behavior and technology.  

Having seen first hand how companies like those work, we can't rule out all sorts of deliberate underhanded tactics - even amung project teams (ie: the IT department not wanting to admit problems to the sales team, so do whatever it takes to make paying account appear operational and thus everything is tickety-boo.) 

I can see them throttling or halting open projects; massaging scan jobs through by hand, and so on. 
In our case, my personal email tone regarding their absenteeism is not the friendliest, so I could also see administrators there applying "discretionary" changes to non-paying projects.

Then again, the saying "never attribute to malice what can be done by incompetence" holds true here too.  I'll try another account, and see if that changes anything.

I do like their product and would love to get DOSBox 'clean' against their scan; even if just a handful of issues wind up to be the big winners.

**Comment by krcroft** [comment]
New account (https://scan.coverity.com/projects/dosbox-staging-unclog-1).

Queue position is even worse!
![2019-12-11_15-00](https://user-images.githubusercontent.com/1557255/70667939-0451e680-1c27-11ea-936b-7b51442e0c95.png)

**Comment by krcroft** [comment]
@dreamer our primary account is now queued at position **306**, after 9 hours passing.  However, at 0.33 jobs/hour, we'll wait another 1,000 hours, or 41 days before being first in the queue.

My other account is still stuck awaiting approval.

**Comment by dreamer** [comment]
First "response" from Synposys ([link](https://community.synopsys.com/s/question/0D72H000003vs0k/attn-were-experiencing-operational-issues-with-polaris?s1oid=00D3000000007Mm&s1nid=0DB340000008S5F&emkind=chatterCommentNotification&s1uid=0052H00000BzPB5&emtm=1576168412515&fromEmail=1&s1ext=0)):

> We apologize for the delay. Our team is switching over to more fully supporting Coverity Scan, but there will be delays as we effect this change. However, Coverity Scan does not use Polaris and there is no connection between behavior on Coverity Scan and Polaris.

**Comment by krcroft** [comment]
10 more hours, position 301, 0.5 jobs/hour. 
ETC: 602 hours or 25 days.

**Comment by krcroft** [comment]
Just under 24 hours since last report.
Now position 297; Coverity Scan only processed 1 job every 6 hours.  
This is a trainwreck in slow-motio ... do they have a single raspberry pi running their public scanning service?

**Comment by krcroft** [comment]
48 hours later, now position 294.  Since their Sunday crash, we've moved 15 places in 8 days.

**Comment by dreamer** [comment]
We got [a response](https://community.synopsys.com/s/question/0D72H000003vsD0/when-coverity-scan-will-be-working-again?s1oid=00D3000000007Mm&s1nid=0DB340000008S5F&emkind=chatterCommentNotification&s1uid=0052H00000BzPB5&emtm=1576540805522&fromEmail=1&s1ext=0). Basically we shouldn't expect it to work until January (at earliest).

On an unrelated note, in I tried to introduce simple regression tests for #94 but it turned out that invocation running `xvfb-run timeout 15s ./src/dosbox <params>` does not behave reliably on our CI and I have no idea why… `xvfb-run` seems to work reliably for our dynamic analysis though.

**Comment by krcroft** [comment]
I'm glad someone at Synopsys finally explained what's going on and what we can expect.  Two or three weeks is fine.. and we still have over 350 active issues flagged if we're hungry in the meantime. 

I wonder if running DOSBox under github's macOS VMs or the Windows VMs have an inbuilt display? (and we can avoid a dummy-headless solution like xvfb).  

Another issue with the Linux VMs is they don't have sound devices, so to exercise that code we'll need to fake out alsa either via dummy sound device or a pulse audio sink. (Maybe we get audio under Windows and macOS too).

**Comment by dreamer** [comment]
Hmm, it seems like our "Config heavy" builds are quite unstable - they often fail due to problem with MSYS2 installation…

**Comment by krcroft** [comment]
When I first saw this, I thought it might be a one-off occurrence, but it's forming a pattern now with almost a 50% (or more) rate. 

Given we rarely see these issues during manually pushed jobs, I've made a PR that simply rolls-around the start time to 4pm GMT, which lands it within "office hours" for a lot of their users.

https://github.com/dreamer/dosbox-staging/pull/98

**Comment by krcroft** [comment]
GitHub and all these broken/throttled connections. 
![Screenshot_20191219-121335_Brave](https://user-images.githubusercontent.com/1557255/71206405-4d262280-2259-11ea-9d71-553dbb011964.jpg)

If their cache was more generous, we could cache all our remotely fetched files (apt/brew/pacman/vcpkg) and only hit them every week or two for updates. 

Actually.. I don't know why GitHub isn't providing their own caching of these popular repos. DOSBox (at 250k LOC) is a heavyweight among most repos, and we still spend most of our VM time downloading and installing packages versus actually building our code.  Github could massively cut their VM bills if they cached or provided pre-canned configs of these.

**Comment by dreamer** [comment]
> GitHub isn't providing their own caching of these popular repos

I think vcpkg repos run on Azure infrastructure (it's Microsoft's tool after all), so additional caching might not be really needed. As for Ubuntu - I am 100% sure VMs do not hit official repos by default, but use Azure-powered mirrors of Ubuntu repos. I have no idea about brew and Chocolatey. MSYS2 is not officially supported still…

**Comment by krcroft** [comment]
> [edit] wait, GCC-9 packages got downloaded from PPAs and not Azure mirrors? What?

Yeah, GitHub's Ubuntu VM's are pre-loaded with PPAs, which is very "non-standard", especially given 19.04 has GCC-9 in its base repository.  

They're using:
- http://ppa.launchpad.net/ansible/ansible/ubuntu
- http://ppa.launchpad.net/apt-fast/stable/ubuntu
- http://ppa.launchpad.net/git-core/ppa/ubuntu
- http://ppa.launchpad.net/hvr/ghc/ubuntu
- http://ppa.launchpad.net/ondrej/php/ubuntu
- http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu

`ubuntu-toolchain-r/test` always provides the latest stable release of GCC, which clobbers the distro's own GCC-9; so that's unfortunate - and additionally stresses Ubuntu's PPA servers.

We could try `rm -f /etc/apt/sources.list.d/*` before `apt-get update`, to avoid installing any of their packages.  It would also speed up the `apt-get update` step.

**Comment by krcroft** [comment]
Propose we close this based on progress this far to prevent regressions:
- individual bug counts now locked in for each architecture and compiler version
- bug counts for clang's and pvs studio's analyzers are locked in.
- automated test-case handling in PR; all tests must pass otherwise the workflow will fail.

**Comment by dreamer** [comment]
Yeah, I agree, time to close this issue. Abovementioned PR is a better place to discuss the few remaining issues. Maybe we'll create smaller, more focused in scope issues for other areas (like unit testing) in the future.
