### ISSUE TITLE
Can't swap floppy disk images

### ISSUE THREAD

**Issue by richard-gravy** [dreamer/dosbox-staging#234]
Hello,
I have mounted two floppy disk images for an installation program using:-
`imgmount a: /tmp/nx211-1.img /tmp/nx211-2.img -t floppy`

This is reflected in the console, which updates with:-
`Mounted FAT volume is FAT12 with 2847 clusters`
`Mounted FAT volume is FAT12 with 2847 clusters`
`Drive A: disk 1 of 2 now active`

I don't seem to be able to swap between the disks, however.  Ctrl+F4 doesn't work.  Other commands seem to be recognised, like Ctrl+F1 for the keymapper or Ctrl+F9 closes Dosbox.

My host environment is Fedora 31 running a Wayland Gnome session.  dosbox-staging is version v0.75.0-pre-664-g694e.

Can anyone else running Gnome check that swapping is available?

**Comment by dreamer** [comment]
As it happens, a fix for broken shortcuts was merged-in only a few minutes ago: #230 :)

Can you re-test with the latest snapshot? I just tested v0.75.0-pre-669-gf1b9e504 and I am able to cycle through 6 installation floppies with Windows 3.11.

**Comment by richard-gravy** [comment]
Now that's service!
Works great, thanks.
