### ISSUE TITLE
Allan Border's Cricket: CDROM: Track 2 failed to seek to byte 9878400, so cancelling playback

### ISSUE THREAD

**Issue by amak79** [dreamer/dosbox-staging#239]
I'm running [Allan Border's Cricket](https://www.mobygames.com/game/allan-borders-cricket) with dosbox-staging (git master) on Gentoo Linux. When the game starts the intro/menu music is played for ~65 seconds. After the music has ended the game attempts to play it again after ~10 seconds, but fails with the following error flooding the terminal:
```
CDROM: Track 2 failed to seek to byte 9878400, so cancelling playback
```
I used `cdrdao` to create an image of the disc and `toc2cue` to convert the TOC file to the following CUE file:
```
FILE "Allan Border's Cricket.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 00:56:00
```
The same BIN/CUE works with Dosbox 0.74-3 without any issues.

**Comment by dreamer** [comment]
Which version of dosbox-staging exactly are you testing? (if you compiled it yourself, you can obtain info using `git describe`)

**Comment by amak79** [comment]
It's always the most recent commit which currently is 2fc67710462037522bd22a3d1730d1da9a569420.

**Comment by krcroft** [comment]
Thanks for the submission and confirming version of staging @amak79 ; I will check it out.

**Comment by krcroft** [comment]
@amak79 I unfortunately don't have access to the CDROM version of this game. 
Feel free to contact me at <krcroft at g m a i l . c o m> if a copy can be made available for testing.  (I will then purge this comment)

**Comment by krcroft** [comment]
Reproduced with binary + cue file and using the game's 'full HD install option'.  
If 'install config to HD' option is used, then the game only plays the file once.
If file-based tracks are used (wav/flac/opus), then the seek error also does not occur. 
Thank for finding this corner case @amak79 !

**Comment by amak79** [comment]
I've tested the fix and I can confirm it's working now. Thanks for taking the time to investigate this issue.

**Comment by krcroft** [comment]
Thanks for the test and quick feedback @amak79
