### ISSUE TITLE
Theme Hospital crash

### ISSUE THREAD

**Issue by nemo93** [dreamer/dosbox-staging#243]
* Description
Game will crash after a while (usually after a few minutes of play during the 1st level).

* To Reproduce
Launch Theme Hospital (HOSPITAL.EXE). I'm using a iso/cd version which is mounted prior launching the game. Start a game as normal, place a room and a few elements. Game will crash at some point.
NOTE: with the current Dosbox SVN (default in Retropie) the crash will occur as well.
NOTE2: I've read somewhere the crash could be due to some instability with Gravis Ultrasound. I've indeed configured the game to use that soundcard. If anyone could confirm that please? I'll do another test with just `sb16`.

* Environment:
Raspbian Jessie (the one shipped with Retropie+all packages up-to-date)
Retropie Version 4.5.18 (latest)
Pi3B+
SDL2 2.0.10 (no dispmanx)
I've compiled Dosbox-staging this morning after I saw the commits for SDL texture.

* Dosbox config
```
fullscreen       = true
vsync            = false
fullresolution   = desktop
windowresolution = desktop
output           = texture
texture_renderer = auto
capture_mouse    = seamless middlerelease
sensitivity      = 100
waitonerror      = true
priority         = higher,normal
mapperfile       = mapper-SVN.map

language = 
machine  = svga_s3
captures = capture
memsize  = 16

frameskip = 0
aspect    = true
scaler = none

core = dynamic
cputype   = auto
cycles = max
cycleup   = 10
cycledown = 20
[...] 

sbtype  = none
sbbase  = 220
irq     = 7
dma     = 1
hdma    = 5
sbmixer = true
oplmode = auto
oplemu  = default
oplrate = 44100
[...]

gus      = true
gusrate  = 44100
gusbase  = 240
gusirq   = 5
gusdma   = 3
ultradir = U:\ULTRASND
```

**Comment by krcroft** [comment]
Can't reproduce this on the Pi (it's been playing in the background for the last couple hours.. midi music plinking away).  I've got a clinic with a 4 items in it (everything I could buy right off the start).

My installation uses the conf below and DOS32a inside the executable. Can you try replacing the extender in `hospital.exe` with DOS32a?  (download DOS32a, then run `sb /r hospital.exe`.

```
pi@retropie:/dev/shm/dosbox/game/hospital $ file hospital.exe 
hospital.exe: MS-DOS executable, LE executable for MS-DOS, DOS/32A DOS extender (embedded)
```

Config (load this plus your baseline config using something like: `/usr/src/dosbox-staging/src/dosbox -conf /home/pi/.dosbox/dosbox-staging-git.conf -conf /path/to/game/dosbox.conf` )
```
[cpu]
core=dynamic
cycles=max 95% limit 30000
cputype=auto

[dosbox]
machine=vesa_nolfb
memsize=24

[midi]
mpu401=intelligent
mididevice=alsa
midiconfig=128:0

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=fast

[gus]
gus=false

[dos]
xms=true
ems=false
umb=true

[speaker]
pcspeaker=false
tandy=off
disney=false
```

**Comment by nemo93** [comment]
* Moving to DOS/32A solved the issue. No more crashing even with Gravis Ultrasound. Yay!
* Note: you not simply have to change the DOS4GW.EXE but also as @dreamer stated to inject DOS32/A within game's executable HOSPITAL.EXE. ([guide](https://www.dosbox.com/wiki/TOOLS:DOS32A))

**Comment by dreamer** [comment]
I really don't remember when I stated, that DOS32/A can be injected in the game's executable, but it doesn't matter (I just don't want to take credit for that info ;)).

Glad it works ok - I created #256 - when implemented it should make this easier for new dosbox-staging users in the future :)
