### ISSUE TITLE
Screen filtering does not work in fullscreen under output=opengl

### ISSUE THREAD

**Issue by NicknineTheEagle** [dreamer/dosbox-staging#245]
output=opengl is supposed to have bilinear fitering applied but, unlike upstream, it only appears to work in windowed mode, not in fullscreen. output=texture is fine.

**Comment by dreamer** [comment]
Are you sure you're not mistaking `glshader=sharp`, which is providing accurate integer scaling with nonbilinear filtering? Can you provide a screenshot?

**Comment by NicknineTheEagle** [comment]
Huh, you're right. This is different from upstream where the default is ``glshader=none``.
