### ISSUE TITLE
Upgrade to SDL2

### ISSUE THREAD

**Issue by dreamer** [dreamer/dosbox-staging#29]
At the moment, the DOSBox code is exclusively SDL1.2 compatible - this is a growing problem, as SDL1.2 is no longer being supported for ~7-8 years at this point - maintainers encourage everyone to move to SDL2, which is a substantial upgrade. Additionally, official releases of DOSBox on Windows use *modified* version od SDL1.2 library (see file: `src/platform/sdl-win32.diff`), which makes it harder to properly reproduce build on Windows.

A lot of users (and some DOSBox devs) don't consider this an issue, as there is 6-year old, so-called "SDL2 patch" (f1b82ef55). However, this patch/thread is not named correctly - it's really a port of DOSBox to Android platform with SDL2 parts attached. This patch has some inherent problems, that (I believe) prevented it from being merged so far:

- +13k lines of code in a single commit
- incompatible with SDL_sound 1.2 (despite information in that thread), breaking the mounts of .cue files
- tries to be compatible with both SDL2 and SDL1.2 on compilation-level by introducing a whole lot of ifdefs in code, making it borderline unmaintainable. In result the code is ifdefed not only per-platform, but also per SDL < 1.2.13, SDL < 2 and SDL >=2, OpenGL and OpenGL ES.

*These are not criticisms of author or his code - author had no other way of suggesting his patch for inclusion in SVN without having direct commit access.*

## Problems with SDL 1.2

- The library is **not maintained any more**
- Game-breaking input issues on Linux (it depends on the game)
- Problems with integration into modern Desktop Environments (e.g. broken Alt-tab)
- Requires dosbox-specific patch to SDL1.2 on Windows
- Non-support for setups using multiple displays (broken in several ways, fix requires specific values in dosbox configuration AND environment variables to trigger specific SDL 1.2 behaviour)
- Problems with support for modern gamepads/joysticks/other input methods
- Problems with input in specific environments filtering input or injecting overlays (e.g. Steam/SteamOS)
- No Vulkan support, no Metal support (which means: sooner or later, there will be no more hardware accelerated renderer on macOS)
- No Wayland support
- Breaking input issues in XWayland in Wayland in ALL games

## Costs/benefits of using SDL2

Costs:

- SDL2 dropped SDL_sound library (this issue will be addressed by #12)
- SDL2 dropped SDL_cdrom library (f1b82ef55 bundles this library, but don't want to include it in dosbox-staging master unless there will be a dedicated programmer, who will maintain it. Physical CD-ROMs are already quite rare in modern computers, and users clinging to their physical CDs should back them up as .iso files sooner rather than later)
- Dropped support for `ddraw` renderer (it is, theoretically, replaced by `direct3d` renderer, but the code was likely never tested)
- The "SDL2 patch" is likely incompatible with a number of other important patches posted on Vogons forum
- No support for OS/2

Benefits

- Testing indicates, that it solves ALL input issues
- Very likely will work fine without patching SDL library on Windows
- Solves most of Desktop Environment integration issues on Linux
- Enables an upgrade path towards implementing Vulkan and Metal renderers
- Enables an upgrade path towards Wayland support
- Dropping OS/2 is actually beneficial from POV of code maintenance
- Provides better scaling by default (I'm not sure if it is as good as scaling implemented by "Pixel Perfect" patch (openglpp renderer), but it's definitely better than current version of DOSBox.
- Removes a number of hacks implemented in DOSBox code for SDL1.2 support on Linux
- Provides additional features and support for modern platforms

## Plan

*This is my suggestion on steps required to resolve this issue, I am open to suggestions/alternative plans*

*edit: leaving original plan in here; revised plan and status update in comments below*

1. Step by step, resolving #12 
2. Replace dependencies on SDL_cdrom, that exist outside of CDROM-related code (included in #28)
3. Remove physical CD-ROM support to avoid SDL_cdrom dependency altogether
4. Remove OS/2 support from DOSBox code
5. Strip "SDL2 patch" out of Android-related and CD-ROM related parts
6. Provide detailed documentation/instructions on converting DOS games distributed on CD to .img files or, even better, .cue files with audio stored in .flac.

Test implementation of Step 5 can be found in 26027c9 - it changes initial +13k lines of code to +704,-966.

**Comment by krcroft** [comment]
@dreamer , this is the first and I believe only objective assessment and accompanying step-by-step plan to upgrade DOSBox to SDL 2.x.

Would it be worth linking your discussion to these vogons threads (and others that you mentioned)? 

 - _"Why is DosBox stuck on SDL 1.x?"_ https://www.vogons.org/viewtopic.php?f=32&t=51652
 -  _"An adaptation to SDL 2.0"_ (NY00123's patch): https://www.vogons.org/viewtopic.php?f=41&t=34770
 - _"DOSBOX SDL2"_ https://www.vogons.org/viewtopic.php?f=32&t=58072
 - _"Dosbox dropping pressed keys?"_ https://www.vogons.org/viewtopic.php?f=31&t=66491

I suspect some decent percent of those participants are interested in having this issue solved.  (However, it might draw trollish comments as well; I'm all for objective discussion, but there's no sense in engaging some of the hostile hyperbole I've seen fly around as well).

**Comment by dreamer** [comment]
Let's not link it on Vogons yet, I suspect SDL2-related responses might derail discussions about merging-in your SDL_sound work and other prerequisites.

BTW, we could learn from experiences of DOSBox-X project: joncampbell123/dosbox-x#306 joncampbell123/dosbox-x#963 - I have a different opinion than DOSBox-X maintainer here - we should move to SDL2 ASAP to avoid as much maintenance burden as possible, and avoid "intermediate state" when both SDL1 and SDL2 are supported at the same time.

**Comment by krcroft** [comment]
Great point; I fully agree in focussing efforts  on the patch and using the DOSBox team's dev platform (source forge) will ensure the most productive discussion (and participants).  Deleting my prior comment, and will eventually drop this too.

**Comment by dreamer** [comment]
I just noticed, that macOS build (Xcode on 10.14) reports 49 `deprecated-declaration` warnings - all of them are pointing to OpenGL functions. I hope GitHub will add a possibility to run  builds on macOS-10.15…

**Comment by krcroft** [comment]
Interesting; are these caused by Apple GL headers perhaps doing something non-standard, or DOSBox's own OpenGL code?  Interesting that Clang doesn't throw those warnings under our other environments.

**Comment by dreamer** [comment]
No, Apple officially deprecated OpenGL more than a year ago - they pushing for adoption of Metal across the applications. Clang does report these warnings (I just never bothered to check what they were about).

**Comment by krcroft** [comment]
Wow.. even more of a fire move to SDL 2.0, now that 2.0.8 supports Apple's Metal interface.

**Comment by krcroft** [comment]
SDL2's input layer will unlock handling of modern joysticks; which has become an issue under SDL1.2 even with the multi-axis patch used by ECE: https://www.vogons.org/viewtopic.php?f=31&t=70136&p=800105#p800105

**Comment by dreamer** [comment]
A month has passed, so a status update:

## Plan
1. Step by step, resolving #12. **(done)** *patches sent upstream, awaiting review*
2. Replace dependencies on SDL_cdrom, that exist outside of CDROM-related code (included in #28) **(done)** *patches sent upstream, awaiting review*
3. Remove OS/2 support from DOSBox code: **(in discussions)** #58 
4. Remove physical CD-ROM support to avoid SDL_cdrom dependency altogether. **(implementing)** *This got split into smaller tasks, I will need to create a separate issue to explain everything that is being done here. I do not go the route of some DOSBox forks, that just slap `#if 0` on the code and call it a day).*
5. Strip "SDL2 patch" out of Android-related and CD-ROM related parts **(implementing)** *largely done - Android port is a separate task to be started after SDL2*
6. Provide detailed documentation/instructions on converting DOS games distributed on CD to .img files or, even better, .cue files with audio stored in .flac. **(not started)**
7. **(new)** Investigate what is the best way of bringing physical CD-ROM support back - this will start after SDL2 will be merged in the master. The details 

Code itself is already written, somewhat tested on Linux (Fedora) and Windows 10, and being polished.  You can build it yourself and test on branch [po/sdl2-7](https://github.com/dreamer/dosbox-staging/commits/po/sdl2-7)

**Comment by krcroft** [comment]
I did a quick test of `po/sdl2-7` with various types of games:
- Wing Commander II
- X-COM I
- Overlord
- Nomad
- Chuck Yeager's Air Combat
- California Games I (CGA, loadfix)
- Shamus (CGA)

They ran clean having expected video and keyboard/mouse input, without any dropped keys.

**Comment by dreamer** [comment]
In another thread I expressed small concern about removal of CD-ROM support, as I believed it might be illegal in some countries (namely: in the UK) to do backups of your legally-owned game CDs. All my searches pointed me at the legalization of UK law regarding personal backups ~2014 and subsequent removal of consumer protections in 2015.

But, as @krcroft pointed out - this does not apply to games, only to Audio/Video. That are even some sources indicating legal precedents from 80s/90s and even stating that in the UK you are allowed 1 personal backup copy of every game you own.

**We are not lawyers, don't treat this as a legal advice.**

Anyways, this moves step (7) of SDL2 upgrade plan back to *"optional, nice to have"* state. Without separate code paths per OS, DOSBox code would be more portable.

Also, CDs from 90s are reaching the end of their effective lifespan as a medium now. Maybe CDs that are plactic-wrapped and stored in proper conditions will be readable for years to come… But after ~25 years, normal CDs are turning unreadable now - we need to encourage users to do backups ASAP.

**Comment by krcroft** [comment]
For those interested, [section 50A of the UK's copyright act](http://www.legislation.gov.uk/ukpga/1988/48/section/50) explicitly allows backup of computer software. This law has been continuously in-force since 1988.  

---
Computer Programs
====
**50A Back up copies**

1. It is not an infringement of copyright for a lawful user of a copy of a computer program to make any back up copy of it which it is necessary for him to have for the purposes of his lawful use.

1. For the purposes of this section and sections 50B [F164, 50BA] and 50C a person is a lawful user of a computer program if (whether under a licence to do any acts restricted by the copyright in the program or otherwise), he has a right to use the program.

1. Where an act is permitted under this section, it is irrelevant whether or not there exists any term or condition in an agreement which purports to prohibit or restrict the act (such terms being, by virtue of section 296A, void).

The copyright act has been attached, and the above reference can be read on page 49 in the PDF. Also note that the document is up to date with all changes known to be in force on or before 10 October 2019 (it's last date of revision).
 
[Copyright, Designs and Patents Act 1988 through Oct-2019.pdf](https://github.com/dreamer/dosbox-staging/files/3940539/Copyright.Designs.and.Patents.Act.1988.through.Oct-2019.pdf)

---

**Comment by krcroft** [comment]
If we consider Wikipedia's statement _"Emulation refers to the ability of a computer program to emulate (or imitate) another program or device"_, then DOSBox's image-mounting ability fits the bill by accurately emulating the both physical media (via file-based representation) and the physical CDROM device (via software).

By enabling DOS games to interface with physical CDROM media, DOSBox functions less like an emulator and more like a hardware compatibility-shim (no different if DOSBox allowed games to interface with circa-90s sound and video cards).   So in this regard, I see dropping physical media support as a move toward becoming more emulation-focused.

**Comment by krcroft** [comment]
Another point: 15 years ago storing countless CDROM images might not be feasible given HDD storage sizes and costs at the time.

Circa-2019 removable media (SD card and USB thumb  sticks) is small, physically robust, low-cost, and can store hundreds of DOS CDROM images.  Even when plugged into early turn-of-the-century hardware (if that's our low-bar for running DOSBox), USB 1.0 speeds (12 Mbit/s) are equivalent to CDROM 8x speeds (8 * 150KBs), which is sufficient for playing DOS games.

So the functional benefits offered by physical CDROM media in DOSBox's early days are far from compelling today given the alternatives.

**Comment by dreamer** [comment]
Major changes landed in master, so it's time for status update:

## Plan

1) **(done)** Step by step, resolving #12; *still waiting for upstream to review/accept patches*
2) **(done)** Replace dependencies on SDL_cdrom, that exist outside of CDROM-related code #28; *still waiting for upstream to review/accept patches*
3) **(done)** Remove OS/2 support from DOSBox code: #58 *not sent upstream yet*
4) **(done)** Remove ASPI CD-ROM interface #81 
5) **(done)** Remove MCI, DX, DIO CD-ROM interfaces #90 
6) **(done)** Remove SDL_cdrom interfaces #95 
7) **(done)** Strip SDL2 patch out of unnecessary parts and merge it in #101 
8) (started) Investigate and fix regressions after move to SDL2
9) (not started) Provide detailed documentation/instructions on converting DOS games distributed on CD to .img files or, even better, .cue files with audio stored in .flac.
10) (optional) Investigate what is the best way of bringing physical CD-ROM support back - this will start after SDL2 will be merged in the master.

**Comment by dreamer** [comment]
A month has passed since the previous status update, and there's nothing new to add in here, really.

Changes regarding point 8 are part of ongoing maintenance work. There are some regressions, some improvements - normal stuff.

We had 0 user complaints about no physical CD-DA support, so work on points 9 and 10 is questionable. It would still be cool to document 9., but it's not really part of SDL2 porting.

Closing this issue; we'll reopen it if needed.

**Comment by vol-2** [comment]
Recently doing some reading on SDL 2.0 and ran across the information that 2.0 has deprecated SDL_CreateYUVOverlay(). Is this true, and if so, does that mean DOSBox staging uses  "2.0 is SDL_Texture()" in it's place when "overlay" is chosen as the output method?
Thanks
