### ISSUE TITLE
CD audio track position is not being updated

### ISSUE THREAD

**Issue by dreamer** [dreamer/dosbox-staging#38]
First reported by in https://www.vogons.org/viewtopic.php?f=32&t=69497&sid=27cde34d8984ff40eb45bd942ad0114c&p=800263#p800263

User **hail-to-the-ryzen** said:
> The CD-DA improvements allow for playback of CD audio in DOS, but the position on any audio track is not updated while playing. Tested with open cubic player that displays the track position and a cue/bin pair for the music.

I confirm this is an issue - tested with fe7600baa92b6154dd8721ca672cb5b8d56c58dc, using [Open Cubic Player (for DOS)](https://www.cubic.org/player/download.html) with [DOS/32A](https://dos32a.narechk.net/index_en.html) renamed to `dos4gw.exe`.

I tested Steam version of Worms (uses audio tracks in OGG/Vorbis):

    $ ~/<path>/src/dosbox .
    # in DOSBox prompt:

    C:\>imgmount D "worms.cue" -t iso -fs iso
    C:\>cd ocp
    C:\>cp
    (select D: and any track to start playing)

Track position is being updated in 0.74-3, so this is a regression.

**Comment by krcroft** [comment]
Thanks for the report and perfect reproduction steps!

**Comment by krcroft** [comment]
Fixed in https://github.com/dreamer/dosbox-staging/commit/06b0507cfcbbf3275bf46082a1ff7ef1f60dc60f

Passed my own tests; close when we have consensus from **hail-to-the-ryzen** and/or @dreamer

**Comment by dreamer** [comment]
For the record, I read through the changes and they seem fine to me. Tested it in Worms and it worked correctly. I left tiny request regarding commit message in code review.

This bug will be closed automatically once review will be merged.

**Comment by krcroft** [comment]
Good stuff; thanks for confirming!

**Comment by dreamer** [comment]
Closing manually, this is fixed now. :)
