### ISSUE TITLE
[branch krcroft/cdda] track upstream Xiph-project cleanup

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#4]
- https://github.com/xiph/ogg/issues/66 (open)
- https://github.com/xiph/opus/issues/146 (open)
- https://github.com/xiph/opusfile/issues/16 (open)
- https://github.com/xiph/speexdsp/issues/28 (open)

**Comment by krcroft** [comment]
I've had to bump MAX_ISSUES from 113 to 154 in `scripts/count-bugs.py` to account for these warnings from Xiph's code. 

I'm not sure when these will be addressed by the Xiph team, however the patch's Makefile always pulls and builds `origin/master` from these repos to ensure DOSBox builds use with the latest-and-greatest Opus decoder (the API is locked in and changes in Xiph's master are always either bug-fixes or stable pushes).

On the other hand, the built-in stb_ and dr_ headers are part of our code and thus we "own" them until the next pull from upstream (which usually involves API and functional changes).  In these cases, I can and do make local fixes to address warnings, such as with stb_vorbis.  

Regarding warnings from Xiph's code: does it make sense for these to be tallied or counted against us, given we're fully dependent on upstream to address them? For example, if we bring DOSBox's warnings down to zero - it would be nice to see that, and not have these Xiph warnings pollute our results.  

That said - it would be still nice to know the number of "3rd party-code warnings", so we have a handle on them.

**Comment by dreamer** [comment]
Don't worry about bumping max issues on your private branch - higher number is almost certainly a result of using newer Clang than available on CI. This check is designed mostly as a "road bump" preventing us from introducing new bugs/warnings by mistake. I was thinking about writing a script for running locally - one that would automatically make 2 static analysis runs (on a commit where current branch branched-off master and latest head) and compare the results.

> I'm not sure when these will be addressed by the Xiph team, however the audio patch's Makefile always pulls and builds Xiph's `origin/master` (…)

This is a problem - such solution would prevent DOSBox (or dosbox-staging) from ever being packaged by Linux distributions (even as a flatpak), so I don't see how it would be accepted by upstream. On the other hand - I am sure it's quite handy for DOSBox-ECE Windows builds (and windows builds in general).

So I would leave it as it is *for the time being*, but long term - replace downloading by proper (optional?) dependency configured via autoconf (similarly as `SDL_sound` is already an optional dependency in upstream). Maybe we can develop better way of looking up dependencies (I hate autoconf), so standard solutions like using `pkg-config` could be used to point build to location/build of dependency of your choosing.

As for Windows: I don't have answers yet - maybe when I'll figure out how to build dosbox on CI in Windows environment we could treat them same way as SDL packages… Not sure.

> Regarding warnings from Xiph's code: does it make sense for these to be tallied or counted against us mingled in with the core DOSBox code?

I don't think so - this is external dependency. I could develop solution to prevent these from being talied (build them separately, without saving output to build.log file), but I'm not a fan of building them in the first place.

> … built-in stb_ and dr_ headers …

These warnings should show up, but I think we could start by isolating only commits introducing these libraries (without actually using them in the rest of the code) - and bump the initial count of warnings to reflect this dependency. Such commit would not affect rest of code, so maybe dosbox maintainers would accept it in svn earlier? This would cut a lot of added lines from your patch and bring it closer to being merged upstream.

**Comment by dreamer** [comment]
Turns out on Windows it should be easy to handle additional libraries by using vcpkg package manager :)

On branch `po/ci-windows-2` I have working build using sdl1 via this method - opus is also packaged (you can see full list of supported packages here: https://repology.org/projects/?inrepo=vcpkg). This gives us additional benefit of simplifying Windows build - we don't need to handle any paths or settings ourselves, all is handled by vcpkg and msbuild.

**Comment by krcroft** [comment]
The xiph libraries have been externalized and we therefore no longer pull in and build their code, so I will closing this issue here bit still track them upstream.
