### ISSUE TITLE
Windows CI shell-running not detecting failed runs

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#41]
Under windows, the build's return code isn't making it up to GitHub's CI run: level.

https://github.com/dreamer/dosbox-staging/runs/299604745#step:6:439

![2019-11-12_14-27](https://user-images.githubusercontent.com/1557255/68716302-c3e44780-0558-11ea-9732-b96389bc23d1.png)

**Comment by krcroft** [comment]
Last good Windows GCC build on master branch:  https://github.com/dreamer/dosbox-staging/runs/299568740, with these flags: `g++  -Wall -pipe -fstack-protector -fdiagnostics-color=always -Ofast  -mno-ms-bitfields`

Next [commit](https://github.com/dreamer/dosbox-staging/commit/4e65c8f69fd808f252e5a25b5df5e3ad643ebd34
) to master fails to build: https://github.com/dreamer/dosbox-staging/runs/299604881, and is using these flags: `g++ -std=c++11 -Wall -pipe -fstack-protector -fdiagnostics-color=always -Ofast  -mno-ms-bitfields`, this is despite the change not touching `configure.ac` or the Makefiles.  It's as if GCC is doing some header or feature inspection and turning on `-std=c++11`.

That should be fine though; so perhaps this is going to cause a ripple-effect through our code to make it play nice with Windows-GCC C++11..

**Comment by krcroft** [comment]
(I suppose we have two issues here; fixing the build is separate versus passing the return-code through) - will open a new one.

**Comment by dreamer** [comment]
This was totally a bug in the wrapper, thanks for diligently pointing it out, and splitting this into two specific issues :)
