### ISSUE TITLE
Linters not crawling files

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#45]
Sorry @dreamer ; I looked at the CI results before the code and should have noticed that there should be more output.

From the output here - https://github.com/dreamer/dosbox-staging/commit/2bfae63f1f9e60854a1c0af005ed7378170f4a46/checks?check_suite_id=311563984

It looks like the two crawlers, `git ls-files | xargs file`, aren't getting off the ground, so we just get the version output from the two linters.  

I pasted it into my local shell:
```
git ls-files￼| head -4
git: 'ls-files￼' is not a git command. See 'git --help'.

(git ls-files) | head -4
.github/workflows/analysis.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
```
I can't explain what's going on here just yet - is git detecting it's writing to a non-interactive stdout pipe, and disabling the command? Where as when I sub-shell it, I hide that fact from it and it happily runs?  

(I'm only thinking this way because I've seen how tar will instantly return success if it detects output redirected to /dev/null `tar -zxvf my.tar.gz > /dev/null`; so to fool tar into actually doing the work you can pipe to cat and then redirect to /dev/null `tar -zxvf my.tar.gz | cat > /dev/null`)

**Comment by krcroft** [comment]
Ok; befuddlement solved - looks like the space between `ls-files` and `|` is a special character.
I just got lucking when I (sub-shell)'d it because it removed that character..

**Comment by dreamer** [comment]
Wait, what? Is there a problem here? Those scripts print tool versions before invoking it. Both tools return an error, which is then propagated to CI - so if ls-files would pick no files, the scripts would fail. I think they are working correctly, but maybe I missed something - feel free to introduce some errors/warnings in scripts to check :)

**Comment by krcroft** [comment]
Yup; problem here. `git ls-files` isn't putting anything out for the pipe chain to digest.

![2019-11-14_14-28](https://user-images.githubusercontent.com/1557255/68901709-43098500-06eb-11ea-8f50-9a0f72a11c18.png)

**Comment by krcroft** [comment]
Atleast my bash shell (or terminal) and GitHub's CI shell seem to choke on the space between git ls-files and the | (when I copy and paste from the script).  Maybe it's some terminal-encoding / ASCII / UTF thing going on?

**Comment by krcroft** [comment]
Copy and paste this into your terminal: `git ls-files￼|` followed by any command. The space before the `|` is what the script is using.  It's differs from `git ls-files |`.

**Comment by dreamer** [comment]
Where did this version of "git ls-files[_](https://graphemica.com/%EF%BF%BC)" came from? GitHub displayed it somewhere?

https://github.com/dreamer/dosbox-staging/runs/303843633#step:6:9

**Comment by krcroft** [comment]
> Where did this version of "git ls-files[_](https://graphemica.com/%EF%BF%BC)" came from? GitHub displayed it somewhere?
> 
> https://github.com/dreamer/dosbox-staging/runs/303843633#step:6:9

I copy and pasted it from GitHub's code listing - but maybe it's just a red hearing, and the script actually is fine but simply doesn't generate output because our code is fully compliant?

**Comment by dreamer** [comment]
Our code is fully compliant :) I just ran both scripts via hexdump, to double check ther are no unicode hidden chars in there.

I can't find a place in GitHub interface, that injects these chars, but this might be due to some browser extensions either us have installed! If it happens with files on your local disk, it might've been caused by some file filters configured in git (but that's rather low probability - they are more of an issue for msysgit for Windows users, not a problem for Linux users).

That being said: I think your concern here is valid, I will make these scripts output list of files, that are being checked - otherwise it's hard to tell, that e.g. shellscript actually does anything.

**Comment by krcroft** [comment]
Found it:

https://github.com/dreamer/dosbox-staging/commit/2bfae63f1f9e60854a1c0af005ed7378170f4a46

![2019-11-14_15-09](https://user-images.githubusercontent.com/1557255/68903752-ee690880-06f0-11ea-80e7-9597c7f5e07c.png)

Copy and pasting that into my terminal: 
```
git ls-files \
> ￼| xargs file
Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-P <parameter=value>] <file> ...
       file -C [-m <magicfiles>]
       file [--help]
```

So combined with that and the 'empty' output I was seeing, made be believe that it wasn't actually running.  Problem solved.

**Comment by dreamer** [comment]
I still can't reproduce it… When I select the text and copy-paste it, the output works in my terminal emulator (tested Tilix and Gnome Terminal)… this is weird.

**Comment by krcroft** [comment]
Interesting; it only happens when I copy from github's diff page (copying from the full source listing is fine). 

Time for me to ditch this default MATE terminal! 
(Help > About: _"A terminal emulator for the MATE desktop 1.20.2"_).

**Comment by dreamer** [comment]
I recommend https://gnunn1.github.io/tilix-web/ ; it works like https://terminator-gtk3.readthedocs.io/en/latest/ but slightly modernized :) I use it with window decorations disabled to maximize screen estate, and usually use 2-4 panes.

**Comment by krcroft** [comment]
Tilix's icon has replace MATE terminal's on my panel :-)
Thanks for the tip @dreamer ! Fonts, colors, and tabs/splits all look great.

Copying and pasting from the diff is still broken:
![2019-11-14_16-13](https://user-images.githubusercontent.com/1557255/68906622-ca5df500-06f9-11ea-8332-503f700c0645.png)

Running Chomium: Version 78.0.3904.70 (Official Build) Built on Ubuntu , running on Ubuntu 19.04 (64-bit)

**Comment by krcroft** [comment]
Aha! It's **Chromium**; copying and pasting from Firefox into Tilix works!
