### ISSUE TITLE
Small bugs in "DIR /P" and irritating CLS

### ISSUE THREAD

**Issue by dreamer** [dreamer/dosbox-staging#75]
These are several inter-connected small bugs, that irritate me:

1) DOSBox accurately emulates "appending newline" after each interactive command. This is exactly how MS-DOS behaves and also cmd.exe (even on Windows 10) - so in this way, this behaviour is "correct". However, this is extremely annoying as it means losing >= 4% of terminal window just to show nothing. 
2) Appending newline "breaks" CLS command, as it assures, that there's always a blank line on top, unlike unix `clear`. This is in line with MS-DOS and Windows cmd.exe, not in line with FreeDOS, PowerShell or bash.
3) Additionally, `DIR` command formats initial lines wrong (making them blend with actual file listing, unlike any real implementation of `DIR`) and other details wrong (e.g. "Bytes" instead of "bytes").
5) Command `PAUSE` appends newline before any key is pressed (unlike MS-DOS or cmd.exe)
6) Additionally, `DIR /P` pauses one line short and injects newline too fast, so the text "Press any key to continue." (should end with "..." btw) is shown twice on the screen, could've easily show 2 more files per screen.
7) FreeDOS and PowerShell fixed these issues and behave the same way as any sane UNIX terminal would do (no additional newlines are injected in interactive mode) - I like FreeDOS choice in this matter. Removing this newline would not affect .BAT scripts in dosbox (newline is appended only in interactive mode). Perhaps the removal of this newline should be a user option, but I don't feel it's necessary.

**Comment by krcroft** [comment]
I coincidentally noticed that 4DOS is also cleaning up whitespace:
```
 Build 162 (Version 7.62) — 25 April 2008:
* The prompt after a CLS now goes to the first, not the second line
```
https://www.4dos.info/v4dos.htm

**Comment by krcroft** [comment]
As long as batch file interpretation is unaffected, then there are only benefits to whitespace or output fixes.  

I also believe there's no reason to reproduced command.com's output to the letter; after all DOSBox's interpreter is deliberately bare-minimum just to support installing and launching games (and little more); and that's the answer that users on vogons get when they complain about DOSBox commands not fully matching a real DOS environment (It's also suggested that _"if you want real DOS, then install MS-DOS into DOSBox"_).

**Comment by dreamer** [comment]
Heh, that's weird answer from Vogons then… I often found myself browsing through filesystem using DOSBox prompt, because i was trying to  improve game compatibility or run a benchmark or something… it would be really nice to have few additional commands (like e.g. working `MORE` or `less`, or unix-like `ls` command). And damn, I would love ctrl+l to clear the screen, like bash does ;).

I think I'll just remove that appended newline - if users will notice or complain, only then I'll consider making it an option.

**Comment by krcroft** [comment]
I'm all for you making as many of these fixes as you like; especially if batch files aren't affected.

Yeah, when it comes to making DOSBox's command environment more feature-complete, I think upstream would only accept additions if they fix the installation or playability of games.  Otherwise, they are considered unnecessary and out-of-scope (and other users will loudly suggest installing command.com or 4dos.com instead :-) )
