### ISSUE TITLE
[branch krcroft/cdda] WAV broken on big-endian architectures

### ISSUE THREAD

**Issue by krcroft** [dreamer/dosbox-staging#9]
An effort is underway to address this:
 1. Replace the original WAV decoder that came with SDL_Sound 1.2 with dr_wav
 2. Work with dr_wav upstream to address current big-endian issues, tracked here: https://github.com/mackron/dr_libs/issues/66

**Comment by dreamer** [comment]
I am in wonder you managed to find a machine with big-endian support in 2019 :) AFAIK all modern architectures are either little-endian or mixed-endian.

**Comment by krcroft** [comment]
Aye, it has been a slog getting it to a useable point (an accelerated xorg depends on the user space driver being configured just right, which in turn depends on the kernel's drm drivers).  

The machine is a circa-1999 PowerMac G4 running a 400 MHz PowerPC 7400 CPU.  I thought it would be relatively quick compared to true 'retro' hardware.. but compiling DOSBox takes about an hour; the render_scalars.cpp file alone takes 11 minutes to build.  The custom kernel took just over 24 hours to build. 

It's pretty exciting though! Proper endian handling in the patches code and all but the wav decoder are working.  There's something nicely anachronistic about playing Opus and FLAC tracks in DOSBox on a machine that was built when Microsoft still supported DOS 7.0!

PS.. the effort to set it up came from wanting to help jmarsh (vogons) test his powerpc dynamic recompiling core - and it's working very well.  Amazing effort by him.

**Comment by dreamer** [comment]
I'm glad it works :) I think you might want to chip your two cents in discussion about C++11 support, as I referred this issue there https://sourceforge.net/p/dosbox/patches/283/

**Comment by krcroft** [comment]
Thanks for the pointer; and I appreciated your balanced out suggestions. I lent some light thoughts; but ultimately I'd like to see some explicit decision either way, as you've asked.

**Comment by krcroft** [comment]
Fixed and tested.

**Comment by barracuda156** [comment]
> I am in wonder you managed to find a machine with big-endian support in 2019 :) AFAIK all modern architectures are either little-endian or mixed-endian.

Writing from 2025, Big-endian machines are well alive :)

**Comment by FeralChild64** [comment]
_Will that thing \_never\_ die?_ - Linus Torvalds on certain big-endian platform :D
